import { NavItemProps } from './Menu.types';

const nav: NavItemProps[] = [
  {
    title: 'Webentwicklung',
    image: {
      src: '/img/webentwicklung.jpg',
      alt: 'Webentwicklung',
      placeholder:
        'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACAhITMkM1EwMFFCLy8vQiccHBwcJyIXFxcXFyIRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/2wBDASIzMzQmNCIYGCIUDg4OFBQODg4OFBEMDAwMDBERDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wgARCAAIAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAID/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhADEAAAAdII/8QAGBAAAgMAAAAAAAAAAAAAAAAAAAIRISL/2gAIAQEAAQUCbRcf/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAwEBPwF//8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAgBAgEBPwF//8QAHRAAAQQCAwAAAAAAAAAAAAAAIQABETFRUoHB0v/aAAgBAQAGPwIeeH2NOu5MznWiv//EABkQAAIDAQAAAAAAAAAAAAAAAAABESExsf/aAAgBAQABPyGemNqmxDFPQ0f/2gAMAwEAAgADAAAAEHv/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/EH//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/EH//xAAXEAEBAQEAAAAAAAAAAAAAAAABABGR/9oACAEBAAE/EAGpWLnNgk//2Q==',
    },
    href: 'https://peter-stuhlmann-webentwicklung.de',
  },
  {
    title: 'Fotografie',
    image: {
      src: '/img/fotografie.jpg',
      alt: 'Fotografie',
      placeholder:
        'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACAhITMkM1EwMFFCLy8vQiccHBwcJyIXFxcXFyIRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/2wBDASIzMzQmNCIYGCIUDg4OFBQODg4OFBEMDAwMDBERDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wgARCAAIAA4DASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAG0w//EABUQAQEAAAAAAAAAAAAAAAAAAAAR/9oACAEBAAEFAqr/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AX//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AX//xAAXEAEAAwAAAAAAAAAAAAAAAAAAgaHw/9oACAEBAAY/Amm3/8QAGhAAAgIDAAAAAAAAAAAAAAAAACEBYREx8P/aAAgBAQABPyGeM2pYtB//2gAMAwEAAgADAAAAEPP/xAAVEQEBAAAAAAAAAAAAAAAAAAAAIf/aAAgBAwEBPxCP/8QAFREBAQAAAAAAAAAAAAAAAAAAACH/2gAIAQIBAT8Qr//EABcQAQEBAQAAAAAAAAAAAAAAAAEAMRH/2gAIAQEAAT8QPNgexIn/AP/Z',
    },
    href: 'https://peter-stuhlmann-fotografie.de',
  },
  {
    title: 'Kalender',
    image: {
      src: '/img/kalender.jpg',
      alt: 'Kalender',
      placeholder:
        'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACAhITMkM1EwMFFCLy8vQiccHBwcJyIXFxcXFyIRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/2wBDASIzMzQmNCIYGCIUDg4OFBQODg4OFBEMDAwMDBERDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAIAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAIRAAAQIGAgMAAAAAAAAAAAAAAQADAhESEyMyIVKDk+P/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwDS8XTEA2DTLaDt7G1IDlgw83p1bZKbreX5eFEUwv/Z',
    },
    href: 'https://ps-kalender.vercel.app',
  },
];

export default nav;
